$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model_component
version: 2
type: command
display_name: Train model
description: Train baseline model
inputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
outputs:
  model_output:
    type: uri_folder
code: ../../../data-science/src   # от components до data-science/src
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38:1
command: echo "Hello AzureML"

# command: >-
#   python train.py
#   --train_data ${{inputs.train_data}}
#   --test_data ${{inputs.test_data}}
#   --out ${{outputs.model_output}}
