type: pipeline
name: full_pipeline_skycore_production
experiment_name: skycore_production_run
display_name: "SkyCore Production Pipeline"
description: Complete pipeline with data prep, train, and register

tags:
  purpose: "production"
  phase: "deployment"

inputs:
  training_data:
    type: uri_file
    path: azureml:used_cars_raw:1

outputs:
  train_data:
    type: uri_folder
    mode: rw_mount
  test_data:
    type: uri_folder
    mode: rw_mount
  model_output:
    type: uri_folder
    mode: rw_mount
  registered_model_info:
    type: uri_folder
    mode: rw_mount

jobs:
  prep_data:
    type: command
    component: azureml:prep_component:3
    compute: azureml:cpu-cluster
    inputs:
      raw_data: ${{parent.inputs.training_data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  train_model:
    type: command
    component: azureml:train_model_component:3
    compute: azureml:cpu-cluster
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
      n_estimators: 100
      max_depth: 10
    outputs:
      model_output: ${{parent.outputs.model_output}}

  register_model:
    type: command
    component: azureml:register_component:3
    compute: azureml:cpu-cluster
    inputs:
      model_name: "skycore_production_model"
      model_path: ${{parent.jobs.train_model.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.registered_model_info}}
