name: full_pipeline
description: End-to-end ML workflow integrating data prep, training, tuning, and registration
type: pipeline

inputs:
  training_data:
    type: uri_file
    path: azureml:used_cars_raw:1

outputs:
  clean_data:
    type: uri_folder
  model_output:
    type: uri_folder
  best_model:
    type: uri_folder

jobs:
  prep_data:
    type: command
    component: azureml:prep_data_component:1
    inputs:
      raw_data: ${{parent.inputs.training_data}}
    outputs:
      clean_data: ${{jobs.prep_data.outputs.clean_data}}

    compute: cpu-cluster

  train_model:
    type: command
    component: azureml:train_model_component:1
    inputs:
      clean_data: ${{jobs.prep_data.outputs.clean_data}}
    outputs:
      model_output: ${{parent.outputs.model_output}}
    compute: cpu-cluster

  tune_model:
    type: command
    component: azureml:tune_model_component:1
    inputs:
      model_output: ${{jobs.train_model.outputs.model_output}}
    outputs:
      best_model: ${{parent.outputs.best_model}}
    compute: cpu-cluster

  register_model:
    type: command
    component: azureml:register_model_component:1
    inputs:
      best_model: ${{jobs.tune_model.outputs.best_model}}
    compute: cpu-cluster


