$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: "SkyCore Pipeline - Bundled CSV"
experiment_name: skycore_used_cars_pipeline

outputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  model_output:
    type: uri_folder
  registered_model_info:
    type: uri_folder

jobs:
  prep_data:
    type: command
    component: azureml:prep_component_bundled:1
    compute: azureml:cpu-cluster
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  train_model:
    type: command
    component: azureml:train_model_component:3
    compute: azureml:cpu-cluster
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
      n_estimators: 200
      max_depth: 10
    outputs:
      model_output: ${{parent.outputs.model_output}}

  register_model:
    type: command
    component: azureml:register_component:3
    compute: azureml:cpu-cluster
    inputs:
      model_name: "skycore_rf_model"
      model_path: ${{parent.jobs.train_model.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.registered_model_info}}
