$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: "SkyCore Pipeline - Account Key Auth (Working Storage)"
experiment_name: skycore_used_cars_pipeline

inputs:
  raw_data:
    type: uri_file
    path: azureml:used_cars_skycore:1
    mode: download

settings:
  default_datastore: azureml:skycore_datastore_accountkey
  default_compute: azureml:cpu-cluster

outputs:
  train_data:
    type: uri_folder
    mode: rw_mount
  test_data:
    type: uri_folder
    mode: rw_mount
  model_output:
    type: uri_folder
    mode: rw_mount
  registered_model_info:
    type: uri_folder
    mode: rw_mount

jobs:
  prep_data:
    type: command
    component: azureml:prep_component:3
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
      test_train_ratio: 0.2
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  train_model:
    type: command
    component: azureml:train_model_component:3
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
      n_estimators: 200
      max_depth: 10
    outputs:
      model_output: ${{parent.outputs.model_output}}

  register_model:
    type: command
    component: azureml:register_component:3
    inputs:
      model_name: "skycore_rf_model_final"
      model_path: ${{parent.jobs.train_model.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.registered_model_info}}
