$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model_component
display_name: train-model
version: 3
type: command
code: ../../../data-science/src
inputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  n_estimators:
    type: integer
    default: 100
  max_depth:
    type: integer
    optional: true
outputs:
  model_output:
    type: uri_folder
command: >-
  python train.py
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --n_estimators ${{inputs.n_estimators}}
  $[[--max_depth ${{inputs.max_depth}}]]
  --model_output ${{outputs.model_output}}
environment: azureml:skycore-train-env-used-cars-mlops-v3:13
