$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_component
display_name: train-model
type: command
code: ../../../data-science/src   # папката, където е train.py
inputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  n_estimators:
    type: integer
  max_depth:
    type: integer
outputs:
  model_output:
    type: uri_folder   # вместо mlflow_model
command: >-
  python train.py
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --model_output ${{outputs.model_output}}
environment: azureml:used-cars-env:fc1dc48e

